services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  openvpn_exporter:
    image: kumina/openvpn-exporter
    container_name: openvpn_exporter
    volumes:
      - /var/log/openvpn/status.log:/etc/openvpn_exporter/server.status
    command:
      - '-openvpn.status_paths=/etc/openvpn_exporter/server.status'
    expose:
      - 9176:9176
    restart: unless-stopped
volumes:
  prom_data: